### ISSUE TITLE
really convincing historical examlpe

### ISSUE THREAD

**Issue by tdhock** [Anirban166/Autocomment-atime-results#20] opened 2024-03-05 18:18 UTC
https://github.com/Rdatatable/data.table/pull/4491 this is the pr which introduced the performance regression
please make a PR from your_data.table/this_branch to your_data.table/old_master
make sure there is a performance test for this case so we will see the regression
@Anirban166

**Comment by Anirban166** [comment] 2024-05-03 09:47
Closing this since it's done (completed [here](https://github.com/Anirban166/data.table/pull/6) for the PR you mentioned or #4491 + we got another historical regression example [here](https://github.com/Anirban166/data.table/pull/8), which replicates #4440)

**Closed by Anirban166** 2024-05-03 09:47 UTC
